### ISSUE TITLE
Detecting the pitch of an AudioBuffer? Without playing the audio back. 

### ISSUE THREAD

**Issue by Catsvilles** [cwilso/PitchDetect#30]
Would it be possible to use this library to detect a pitch of Wav samples, decoded audio buffers, without actually playing the audio? Thank you!

**Comment by TeHMoroS** [comment]
You can actually use the AudioBuffer class. It has a getChannelData() function that returns a Float32Array of samples from the specified channel. That array will contain the whole AudioBuffer data from the specified channel (with values ranging from -1 to 1), which in turn you can use with the auto-correlation function. :)
